import type { Metadata } from "next";
import { Inter, Cormorant_Garamond } from "next/font/google";
import "./globals.css";
import Header from '@/components/Header'
import { CartProvider } from '@/context/CartContext'
import CartDrawer from '@/components/CartDrawer'
import ConditionalHeader from '@/components/ConditionalHeader'
import { WishListProvider } from '@/context/WishListContext'
import WishlistDrawer from '@/components/WishlistDrawer'
import Script from 'next/script'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-cormorant",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt">
      <body
        className={`${inter.variable} ${cormorant.variable} antialiased`}
      >
        <Script src="https://widget.cloudinary.com/v2.0/global/all.js" strategy="beforeInteractive" />
        <CartProvider>
          <WishListProvider>
            <ConditionalHeader />
            <CartDrawer />
            <WishlistDrawer />
            {children}
          </WishListProvider>
        </CartProvider>
      </body>
    </html>
  );
}
